// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const errorMsg = "Supabase environment variables (VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY) are missing. " +
    "If you are running locally, check your .env file. " +
    "If you have deployed the site, ensure these variables are set in your hosting provider's (e.g., Netlify) environment settings.";
  console.error(errorMsg);
  // Throwing a standard error that will be caught by the app's error boundary if it exists,
  // or shown in the console to help debug the "blank screen" issue.
  throw new Error(errorMsg);
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});